-- MySQL Script generated by MySQL Workbench
-- Wed Dec 14 21:42:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bazar_digital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bazar_digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bazar_digital` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bazar_digital` ;

-- -----------------------------------------------------
-- Table `bazar_digital`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`type` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bazar_digital`.`artículos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`artículos` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`artículos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `descripción` VARCHAR(600) NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  `uso_profesional` VARCHAR(45) NOT NULL,
  `type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type_articulos`
    FOREIGN KEY (`type_id`)
    REFERENCES `bazar_digital`.`type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `type_articulos_idx` ON `bazar_digital`.`artículos` (`type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bazar_digital`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`roles` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bazar_digital`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`empleados` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`empleados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `sueldo` INT NOT NULL,
  `roles_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `roles_empleados`
    FOREIGN KEY (`roles_id`)
    REFERENCES `bazar_digital`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `roles_empleados_idx` ON `bazar_digital`.`empleados` (`roles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bazar_digital`.`bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`bodega` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`bodega` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empleados_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bodega_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `bazar_digital`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_bodega_empleados1_idx` ON `bazar_digital`.`bodega` (`empleados_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bazar_digital`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`caja` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`caja` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dinero` INT UNSIGNED NOT NULL,
  `empleados_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_caja_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `bazar_digital`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_caja_empleados1_idx` ON `bazar_digital`.`caja` (`empleados_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bazar_digital`.`medios_de_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`medios_de_pagos` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`medios_de_pagos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bazar_digital`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bazar_digital`.`ventas` ;

CREATE TABLE IF NOT EXISTS `bazar_digital`.`ventas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `artículos_id` INT UNSIGNED NOT NULL,
  `compra_total` INT NOT NULL,
  `medios_de_pagos_id` INT UNSIGNED NOT NULL,
  `empleados_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ventas_medios_de_pagos1`
    FOREIGN KEY (`medios_de_pagos_id`)
    REFERENCES `bazar_digital`.`medios_de_pagos` (`id`),
  CONSTRAINT `fk_ventas_artículos1`
    FOREIGN KEY (`artículos_id`)
    REFERENCES `bazar_digital`.`artículos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `bazar_digital`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_ventas_medios_de_pagos1_idx` ON `bazar_digital`.`ventas` (`medios_de_pagos_id` ASC) VISIBLE;

CREATE INDEX `fk_ventas_artículos1_idx` ON `bazar_digital`.`ventas` (`artículos_id` ASC) VISIBLE;

CREATE INDEX `fk_ventas_empleados1_idx` ON `bazar_digital`.`ventas` (`empleados_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
